### ISSUE TITLE
Infinite sorting

### ISSUE THREAD

**Issue by justendmeplease** [FrostbyteGames1/Frostbytes-Improved-Inventory#4] opened 2024-05-01 23:04 UTC
Whenever I open any inventory it is sorted infinitely which is not only kinda annoying but also ends up crashing my game if I open a chest.

**Comment by FrostbyteGames1** [comment] 2024-05-02 17:17
What version of the mod are you using, and what is your sort key?

**Comment by Patrykowski8** [comment] 2024-05-05 07:07
I have the same problem. I have version 1.20.6, sorting does not work (I use the middle mouse button). I also get kicked from the game after opening the chest

**Comment by FrostbyteGames1** [comment] 2024-05-05 15:41
I have found the source of the crash, and it should be resolved as of v1.7.2.

**Comment by FrostbyteGames1** [comment] 2024-05-06 16:46
What container(s) does sorting not work for? And is it specific to one gamemode?

**Comment by Laser123454321** [comment] 2024-05-07 23:04
I have the same issue, running 1.7.3 on MC 1.20.6 survival multiplayer opening and sorting a standard double chest. Still causes game crash.

**Comment by FrostbyteGames1** [comment] 2024-05-07 23:21
@Laser123454321 Can you provide the log/crash report?

**Comment by Laser123454321** [comment] 2024-05-09 02:04
Not a crash exactly, so no crash log, main minecraft log just reports
"[Render thread/WARN]: Client disconnected with reason: Timed out"

I took video, here is a link
https://youtu.be/kM1Gt42B-z8

**Comment by FrostbyteGames1** [comment] 2024-05-09 21:46
I've just uploaded v1.7.4 to Modrinth and Curseforge, which should (hopefully) resolve the desync issue.

**Comment by FrostbyteGames1** [comment] 2024-05-20 17:26
The issue is confirmed as resolved as of v1.7.7. This version includes a config option to limit the number of interactions created each game tick. The timeout issue is resolved by setting this config option to ~30.

**Closed by FrostbyteGames1** 2024-05-20 17:26 UTC
Labels: bug
